language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "pip install werkzeug"
  - "python setup.py -q install"
# command to run tests
script: python tests/unit_test/base_test.py 